"""fix_options.py — Rewrite all MCQ option texts: equal length, tricky wrong answers."""
import json, sys
sys.path.insert(0, '.')
from q_data import ALL_QUESTIONS

# {id: (correct_text, wrong1, wrong2, wrong3)}  — all ~same length, all plausible
N = {
 1:("Distributed transactions across services using local transaction sequences","Service-to-service load balancing using consistent hashing across nodes","API routing with SSL termination and header transformation logic","Health monitoring and automatic pod restarts on liveness failure"),
 2:("Opens and fails fast when failure rate exceeds configured threshold","Retries failed requests with exponential backoff and random jitter","Routes traffic to standby replicas when primary service is slow","Queues incoming requests until the downstream service fully recovers"),
 3:("Auth, rate limiting, routing, and SSL termination at entry point","Manages distributed transactions across upstream microservices atomically","Stores shared service state in a distributed in-memory cache","Deploys microservices to Kubernetes clusters via built-in CI/CD"),
 4:("Orchestration — central orchestrator owns and tracks the complete flow","Choreography — event bus makes every flow step easily traceable","Both are equally observable using distributed tracing infrastructure","Neither supports end-to-end visibility without custom instrumentation"),
 5:("Infrastructure sidecar proxies intercept traffic with zero code changes","Application-layer interceptors require library upgrades in each service","Database-layer JDBC proxies require driver configuration per service","Build-time pipeline injection requires no runtime container changes"),
 6:("Incrementally migrate a monolith to microservices via proxy routing","Toggle feature flags for gradual activation of each new service","Deprecate unused service endpoints progressively via gateway routing","Manage backward-compatible versioning across service boundaries cleanly"),
 7:("Availability and Partition Tolerance with eventual consistency model","Consistency and Partition Tolerance sacrificing availability entirely","All three simultaneously via distributed saga orchestration pattern","Consistency and Availability using synchronous cross-region replication"),
 8:("Instantly switches load balancer to fully-tested new environment","Canary-releases 5% of traffic to new version per deployment hour","Rolls pods one by one while health checks pass continuously","Uses feature flags in code to gate new behavior per user"),
 9:("Separates read query models from write command models independently","Separates internal service APIs from external third-party integrations","Separates synchronous REST calls from asynchronous event-driven flows","Separates business logic layer from underlying database persistence"),
10:("Runs in same pod as main container sharing network namespace","Runs as separate microservice deployments managed by API gateway","Runs in database tier intercepting queries transparently per service","Runs in shared infra pods monitoring all application services"),
11:("Protocol Buffers providing binary-encoded schema-validated compact messages","JSON with field name dictionary compression and streaming support","MessagePack with type-aware binary serialization and fast decoding","Apache Avro with schema evolution and row-oriented binary encoding"),
12:("Liveness restarts failing container; Readiness removes from endpoints only","Liveness uses HTTP only; Readiness uses TCP socket probes only","Liveness checks DB health; Readiness checks application startup state","Both probe types trigger full pod restart on failure threshold"),
13:("Atomically persists DB change and publishes event in one transaction","Persists circuit breaker state across service restarts consistently","Prevents duplicate message processing by tracking idempotency keys","Handles service discovery failures when registry becomes unavailable"),
14:("Ship compartments — one flooded area leaves rest of ship intact","A database index preventing sequential scans under concurrent load","A CDN edge layer absorbing traffic before hitting origin servers","An API rate limiter distributing load across backend server pools"),
15:("Shares a database with sibling services for development convenience","Is independently deployable without coordinating other service releases","Is loosely coupled with well-defined contract-based interfaces","Has single responsibility aligned to a bounded business domain"),
16:("Multiple identical requests produce the same result as one request","API is fully stateless and holds no session between requests","API supports multiple protocols including gRPC REST and GraphQL","Response is always served from a distributed read-through cache"),
17:("Single named timed unit of work within a distributed trace","The entire request journey across all services end to end","A database query execution plan with estimated and actual cost","A recorded network hop between two consecutive microservice pods"),
18:("Allows bursts up to bucket capacity while enforcing average rate","Counts requests in fixed time windows and rejects above limit","Blocks all requests immediately once per-second threshold is exceeded","Queues excess requests indefinitely until the next refill window"),
19:("Graceful degraded response when a downstream service is unavailable","Terminates and restarts the service on any unrecoverable error","Retries infinitely with exponential backoff until the service returns","Returns HTTP 500 immediately to signal upstream circuit breakers"),
20:("Complete audit trail, time-travel queries, and state rebuild from events","Simpler data model removing need for complex schema migrations","Significantly reduced storage costs compared to relational databases","Faster write throughput than RDBMS for high-volume transactions"),
21:("Stable internal virtual IP accessible only within the cluster","Exposes service externally via cloud load balancer with public IP","Forwards traffic to a fixed external IP outside the cluster","Maps service DNS name to an external CNAME endpoint address"),
22:("Dynamic directory of healthy service instances and their addresses","API documentation and OpenAPI specifications for all registered services","Source code repositories and build artifacts per microservice version","Database schema definitions and migration history per service team"),
23:("An immediate response is needed before continuing the operation","Decoupling producers and consumers is the primary design constraint","The operation may run in background and take several minutes","Guaranteed-delivery reliability is needed across service restart cycles"),
24:("Gradual risk reduction — small traffic % tests new version first","Faster full-deployment with zero additional infrastructure cost needed","Completely eliminates integration testing requirements in staging environments","Supports zero-downtime database schema migration out of the box"),
25:("Eventual consistency via events and saga compensating transactions","Serializable isolation guaranteeing strict global transaction ordering","Strong linearizability ensuring cross-service global ordering always","Read-your-writes consistency enforced globally via sticky session routing"),
26:("Horizontal scaling — each partition assigned to exactly one consumer","Message deduplication via idempotency keys across all producers","Priority ordering of messages across high-traffic topic partitions","Shared persistent checkpoint storage for all consumer group offsets"),
27:("Within a single partition only — no ordering across partitions","Across the entire topic via a global monotonic sequence number","Per producer instance using producer ID and sequence numbers","Across consumer groups consuming the same topic simultaneously"),
28:("Kafka retains by time or size; RabbitMQ deletes after ack","RabbitMQ retains messages for configurable duration regardless of ack","Both delete messages immediately after consumer acknowledgment received","Kafka deletes messages once all consumer groups have consumed them"),
29:("Delivered at least once; duplicates possible if consumer fails pre-commit","Guaranteed exactly once with no duplicates under any failure","May be both lost and duplicated depending on network partition","May be silently lost before consumer reads on broker failure"),
30:("Fail after max retries — isolated for manual inspection and replay","Older than the configured topic time-based retention period","Accessed more often than configured hot-key frequency threshold","Archived to cold object storage for long-term compliance needs"),
31:("Writes succeed if two-plus ISR replicas ack; survives one failure","All three replicas must acknowledge before producer write completes","Data replicated to exactly two brokers in the ISR set","Consumers read simultaneously from two ISR replicas in parallel"),
32:("All bound queues unconditionally regardless of any routing key","Only queues whose routing key matches the message exactly","Queues whose binding pattern matches the message topic wildcard","Queues selected by matching specific message header attribute values"),
33:("Stateful stream processing — joins, aggregations, windowing, exactly-once","Runs batch processing jobs against historical datasets on separate cluster","A plain consumer with a more modern and ergonomic API","Identical functionality as consumer but requires a separate cluster"),
34:("Duplicate messages caused by producer retries on transient failures","Consumer rebalancing triggered by slow processing within the group","Out-of-order message delivery when using multiple topic partitions","Data loss when brokers fail before replicating to ISR set"),
35:("Monotonically increasing integer identifying each message position in partition","Lag between producer write time and consumer processing time in ms","Number of partitions currently assigned to this consumer instance","Replication delay between leader and follower ISR replica brokers"),
36:("Fanout delivers one copy to every subscriber; work queue to one worker","Work queue uses priority ordering; fanout uses strict FIFO order","Fanout routes to exactly one consumer; work queue broadcasts to all","Both deliver identical semantics differing only in routing key format"),
37:("Mechanism for consumers to signal producers to slow down sending","Network congestion from excessive concurrent broker client connections","Replication lag accumulating between leader and follower ISR replicas","Dead letter queue filling from repeated message processing failures"),
38:("Retains only latest value per key — removes older superseded records","Retains all messages within the time-based retention period window","Read-only archival of historical data for compliance and auditing","Retains only high-compression-ratio messages after segment compaction"),
39:("SQS managed work queue with built-in visibility timeout handling","Kafka — native exactly-once via transactional producer and consumer API","NATS JetStream — distributed persistence with consumer group tracking","RabbitMQ — flexible exchange-based routing for complex topology needs"),
40:("Consistently failing message that blocks queue or partition consumption","Message containing malicious payload designed to attack the consumer","Encrypted message the consumer cannot deserialize or decode correctly","Shutdown signal sent to gracefully terminate all consumer goroutines"),
41:("Consumer group committed offsets for fault-tolerant offset tracking","Broker inter-node configuration and metadata for cluster coordination","Schema definitions for all Avro and Protobuf registered message types","Topic-level ACL policies and consumer TLS authentication tokens"),
42:("Removes ZooKeeper using internal Raft-based metadata quorum instead","Kubernetes-native operator for automated Kafka cluster lifecycle management","Redesigned consumer rebalancing protocol drastically reducing rebalance time","New high-throughput compression algorithm optimized for large message batches"),
43:("Tune max.poll.interval.ms, reduce poll records, process async with care","Use a smaller consumer group with fewer instances per topic","Decrease message payload size to speed up per-message processing","Increase partition count so each consumer handles fewer records"),
44:("Enforces schema compatibility and stores Avro/Protobuf schemas centrally","Provides a REST proxy API for producing consuming without JVM","Stores broker TLS certificates and ACL rules for authentication","Caches topic metadata and broker addresses for faster client lookups"),
45:("Time to accumulate messages in a batch before network send","Maximum wait duration for broker acknowledgment after message send","Maximum time before message expires and is dropped from topic","Connection establishment timeout when first connecting to broker cluster"),
46:("Latest produced offset minus consumer committed offset — how far behind","Count of inactive or idle consumer instances within the group","Disk I/O latency on broker storage when flushing log segments","Replication delay between ISR leader and followers on the broker"),
47:("Low-latency request-reply, IoT, or simple pub/sub with simpler operations","Long message retention for full replay and event sourcing patterns","Multi-consumer fan-out with offset tracking and replay capabilities","High-throughput log compaction and stream processing with windowing"),
48:("Atomic write across partitions plus offset commit for exactly-once semantics","Batch import of messages from external sources into Kafka topics","ACID transactions bridging Kafka and an underlying relational database","Financial transaction processing pipeline with end-to-end audit trail"),
49:("Temporal decoupling — producer and consumer need not be online simultaneously","Significantly smaller message payload size compared to JSON over REST","Sub-millisecond delivery latency compared to HTTP round-trip overhead","End-to-end TLS encryption unavailable in standard REST API calls"),
50:("Per-queue with single consumer; breaks with competing consumers or priority","Always guaranteed across all consumer types with FIFO queue mode","Only with direct exchange type and exact single-level routing keys","Never guaranteed in any RabbitMQ configuration unlike Kafka ordering"),
51:("No lock contention — atomic ops without mutex yield 100k+ ops/sec","Cannot handle more than one client connection at any time","Only a single key can be accessed per request at once","Always slower than multi-threaded caches like Memcached in benchmarks"),
52:("Sorted Set — O(log N) rank and score lookup per member","Hash storing each score as a field with O(1) point lookup","List with scores kept in sorted insertion order on write","String with serialized JSON blob of the entire ranked list"),
53:("Concurrent requests for an expired hot key all hit the database","Redis running out of memory and evicting all recently cached keys","Network congestion between Redis cluster nodes during slot rebalancing","Multiple clients concurrently writing to the same popular key"),
54:("AOF fsync every second — good throughput with one-second data loss","AOF fsync on every command write — durable but slowest option","RDB periodic snapshot only — fastest restart but minutes of loss","No persistence configured — highest throughput for pure ephemeral caching"),
55:("Monitors master health and auto-promotes replica on master failure","Shards data horizontally across multiple Redis master nodes automatically","Persists data to disk using configurable AOF and RDB strategies","Pre-warms cache by loading frequently accessed data on startup"),
56:("16384 slots distributed evenly across all master nodes in cluster","65536 slots for finer-grained distribution with many cluster nodes","4096 slots matching maximum supported physical node count in cluster","1024 slots providing coarse-grained distribution across small cluster setups"),
57:("Atomic SET only if key does not exist — basis for locks","Sets multiple key-value pairs atomically in one pipelined operation","Sets a key that always overrides any existing expiration time","Sets a key guaranteeing no eviction regardless of memory pressure"),
58:("Writes to cache and DB synchronously — reads always consistent","Writes to cache only and flushes asynchronously to database later","Writes to a behind-queue for batched database persistence on schedule","Writes to DB only and populates cache lazily on first miss"),
59:("Approximate cardinality counting in fixed 12 KB regardless of input size","Time-series data storage with millisecond-precision timestamp per data point","Full-text search over string values using inverted index structures","Geospatial proximity queries using Geohash-encoded sorted set scores"),
60:("Pub/Sub loses messages for offline subscribers; Streams persist with groups","Redis Streams are significantly slower than Pub/Sub for broadcast","Both are functionally identical with different API command naming only","Pub/Sub supports replay from offset; Streams require explicit XREAD calls"),
61:("Least Frequently Used keys across all keys — better for skewed access","Least Recently Used keys across all keys in the full keyspace","Keys with shortest remaining TTL across the entire keyspace evicted","Randomly selected keys across all keyspace regardless of any pattern"),
62:("Fault-tolerant distributed locking across N independent Redis nodes with quorum","Consistent key hashing for even distribution across Redis cluster nodes","Distributed rate limiting using atomic INCR with short TTL expiry","Cross-datacenter replication with active-active Redis cluster topology support"),
63:("Check cache — on miss fetch DB, populate cache, return result","Preload all database records into cache eagerly on application startup","Write to cache first; cache asynchronously propagates writes to database","App writes to DB; separate CDC pipeline asynchronously updates cache"),
64:("One key receives disproportionate traffic overwhelming its single owning shard","A key causes cache stampede when its TTL expires simultaneously","A key with enormous value causes memory fragmentation across shards","A key with no TTL grows unboundedly until memory is exhausted"),
65:("Lua script — INCR then EXPIRE on first call only atomically","SET with NX and EX flags for conditional creation with expiry","MULTI/EXEC transaction block combining INCR and EXPIRE atomically","Two separate INCR then EXPIRE commands in sequential pipeline calls"),
66:("Atomic batch execution of queued commands without any interleaving allowed","Multi-node connection pooling to distribute commands across cluster shards","Multi-key batch operations with automatic hash-slot routing per key","Pub/Sub channel subscription management across multiple named channels"),
67:("Sorted Set — geo coordinates encoded as 52-bit Geohash integer scores","Hash storing latitude and longitude as separate named fields per member","Bit array using grid-cell coordinates for compact spatial indexing","Doubly linked list with entries sorted by computed proximity score"),
68:("Queries for non-existent keys bypass cache and always hammer the DB","Attacker bypassing Redis authentication to read sensitive cached keys","Cache reads becoming slower than direct DB queries unexpectedly","Cache capacity exhausted by too many distinct actively-cached key entries"),
69:("Compact per-user boolean flags — e.g. daily active user tracking","Encrypting sensitive data using bitwise XOR with a secret mask","Storing binary file contents such as serialized objects or images","Storing IPv4 and IPv6 addresses as compact 32/128-bit integers"),
70:("Batches multiple commands into one network round trip reducing RTT","Data transformation pipeline processing stream results on Redis server","Priority-based command execution ordering for time-critical operations","Replicates all write commands from master to replica nodes immediately"),
71:("Data loss if cache fails before async background flush to DB","Cache always serves stale reads because writes bypass DB entirely","Database overload caused by every write bypassing the cache layer","Higher write latency since both cache and DB must synchronously ack"),
72:("Key hash slot lives on different node — client must redirect request","Cluster is undergoing rolling maintenance and temporarily unavailable now","Requested key value is too large for this node to serve","Key was deleted and its hash slot is now marked empty"),
73:("Cache with TTL plus background refresh using stale-while-revalidate pattern","Cache permanently with no TTL since recomputation is prohibitively expensive","Cache only in application JVM heap to avoid network round trips","Avoid caching computed results as they risk returning stale responses"),
74:("Internal memory encoding — ziplist, hashtable, or skiplist for the key","Persistence format encoding used for RDB snapshot or AOF log","Network wire protocol encoding between Redis client and server nodes","Encryption algorithm applied to protect sensitive cached key values"),
75:("Redis Sentinel or Redis Cluster deployed via Helm chart with StatefulSets","Single Redis pod with a persistent volume claim for data durability","Redis sidecar container injected into every application pod at runtime","Multiple independent Redis pods queried via client-side consistent hashing"),
76:("Eliminates expensive TCP and auth handshake overhead per new request","Speeds up slow queries by precompiling and caching execution plans","Reduces replication lag between primary and read replica databases","Prevents schema migration conflicts when multiple services update tables"),
77:("Keeps multiple row versions so concurrent readers never block writers","Uses optimistic locking with version columns for all write operations","Acquires shared read locks preventing concurrent writes from proceeding","Stores only WAL entries without ever modifying actual data pages"),
78:("Contains all query columns — heap table access entirely eliminated","A partial index covering only rows matching a specific WHERE filter","An index spanning multiple joined tables to speed up JOIN plans","An index on every column in the table as wide composite"),
79:("1 query fetches N parents then N queries fetch each child set","A single query taking N+1 seconds due to a missing index","Opening N+1 concurrent connections for parallel execution per request","Creating N+1 conflicting indexes that degrade write throughput severely"),
80:("Often unhelpful — full scan may be faster with poor selectivity","Always beneficial — any filter condition reduces the rows examined","Best index type for boolean and low-cardinality enum columns","Only useful when combined with a sorted clustered B-tree index"),
81:("No suitable index exists or planner decides sequential scan is faster","The query uses an existing index to satisfy WHERE conditions","The table contains zero rows needing no index scan overhead","The query joins two or more tables using nested loop plans"),
82:("Ratio of bytes written to disk versus bytes written by application","Replication factor causing multiple copies of each write across nodes","Write errors triggering retries that each amplify the total request","Single client issuing many writes to different shards simultaneously"),
83:("One shard receives disproportionate traffic from a skewed shard key","A shard server overheats causing I/O throttling and performance drops","A shard has too many replicas causing excessive replication fan-out","Shard data size exceeds the maximum configured per-shard capacity"),
84:("Precomputed physically-stored query result that supports indexing and refresh","A virtual view that re-executes underlying query on every access","A data type for storing structured pre-serialized binary object blobs","A read-only logical replica of a primary table across regions"),
85:("Cassandra sacrifices consistency; HBase sacrifices availability on partition","Cassandra sacrifices availability; HBase sacrifices consistency always","Both sacrifice partition tolerance relying on reliable network links","Both are CA systems avoiding partition tolerance trade-off entirely"),
86:("Optimistic checks version on write conflict; Pessimistic locks row on read","Optimistic uses DB-level locks; Pessimistic uses application-level locks","No meaningful difference — both mechanisms prevent concurrent write conflicts","Optimistic for NoSQL only; Pessimistic exclusively for SQL databases"),
87:("B-tree ordered index supports range, equality, ORDER BY, and MIN/MAX","GIN full-text index optimized for text search and JSONB queries","Bitmap index designed for low-cardinality analytical warehouse workloads","Hash index providing O(1) equality lookups with compact storage size"),
88:("All connections in use — new requests timeout waiting to borrow","Too many indexes consuming storage and causing slow rebuild operations","Disk I/O saturation from unindexed sequential scans on large tables","Database storage volume full preventing any new row insert operations"),
89:("Durability and crash recovery — changes logged before data pages written","In-memory write cache reducing disk I/O for frequently updated rows","Index rebuild log tracking structural changes to B-tree page splits","Replication-only mechanism with no role in local crash recovery"),
90:("Embedded means inline in parent; reference means separate doc with ID","Embedded means separate collection; reference means inline in same doc","No functional difference — WiredTiger stores both formats identically","References only valid for array fields; embedded only for objects"),
91:("Delay between primary write and replica sync — stale reads possible","Slow query execution on primary causing write latency spikes","Network round-trip latency from application server to database host","Background index rebuild blocking reads on primary during maintenance"),
92:("Reads may return stale data milliseconds after a write completes","Data immediately consistent across all three AZ replicas after write","DynamoDB never achieves full consistency across all partition replicas","Only one replica is ever updated per write for efficiency"),
93:("Equality filters first then range — most-filtered column placed leftmost","Highest cardinality column always first regardless of query filter type","Alphabetical column ordering for deterministic and reproducible index layout","Primary key column always first in any composite index definition"),
94:("Splits large table for partition pruning, maintenance, and I/O locality","Reduces column count per table to improve vertical query performance","Replaces missing indexes by splitting table on frequently filtered range","Enables per-tenant data isolation with separate logical table segments"),
95:("Minimum replica count that must respond for an operation to succeed","Total number of replicas configured for each distributed database shard","A distributed consensus algorithm like Raft or Paxos for elections","A mechanism for acquiring distributed locks across multiple database nodes"),
96:("JSONB stored binary — faster queries and supports GIN index types","JSONB is plain text preserving whitespace; JSON is compressed binary","No practical difference — both support GIN BTREE and BRIN indexes","JSONB stores only arrays; JSON stores only object key-value types"),
97:("Intentional redundancy added for read performance at update complexity cost","Removing all foreign keys to eliminate join overhead on reads","Converting a normalized SQL schema into a NoSQL document data model","Splitting large tables into smaller partitions to reduce page contention"),
98:("Re-executing same filter query returns new rows inserted concurrently","A read silently returning empty result without error or exception","Reading a row deleted by another concurrent transaction in the table","Reading uncommitted dirty data written by a concurrent write transaction"),
99:("High write throughput with partition key-based lookups by design","Complex multi-table JOINs for flexible relational analytical queries","Ad-hoc analytical queries with schema-on-read and aggregation support","Strict ACID transactions with serializable isolation across all replicas"),
100:("Logs queries exceeding time threshold for performance investigation and tuning","Logs every executed query for comprehensive audit trail and compliance","Logs queries failing due to syntax errors or constraint violations","Logs only DDL statements like CREATE TABLE and ALTER INDEX"),
101:("Hash/encode short code, store in DB plus Redis, use 302 redirect","Store long URL as primary key mapped to short code in RDBMS","Use sequential integer IDs only with no caching layer added","Store all URL mappings in distributed in-memory storage only"),
102:("Nodes on a ring — adding/removing only remaps 1/N keys","A hash function always returning identical output for identical input","Ensures every cache node always receives exactly equal traffic volume","An HTTP-level load balancing algorithm for API gateway route distribution"),
103:("Token bucket or sliding window counter in Redis with per-user TTL","Count all requests in each application server memory independently","Database table with one row per request and a TTL column","Block IPs exceeding rate limits at the DNS resolution layer"),
104:("Globally unique, time-sortable, generated without central coordination needed","Must be human-readable descriptive strings for easy developer debugging","Must be strictly sequential integers from a single central counter","Must conform to standard UUID v4 format for cross-system use"),
105:("Event-driven API to Kafka to per-channel workers with preference routing","Direct HTTP push to each user device from the API server","Store notifications in DB then poll every second from clients","Single-threaded sequential sender processing all notifications one at a time"),
106:("Geographically distributed edge servers cache content close to users","A distributed application-layer cache collocated in the microservice cluster","A multi-region database replication strategy for read-heavy workloads","A content management microservice routing requests by geographic location"),
107:("Redundancy at each tier — multiple LBs, app servers, DB replicas","Add more CPU cores and RAM capacity to a single server","Use faster NVMe SSDs to reduce hardware failure probability overall","Increase all service timeout values so failures cascade more slowly"),
108:("WebSockets for real-time, queues for offline delivery, NoSQL for history","Store all messages in a single relational RDBMS with ACID transactions","HTTP long-polling every second per connected client device connection","Store all messages in Redis with no disk persistence configured"),
109:("Split database by domain — users DB, products DB, orders DB separate","Splitting rows of the same large table horizontally across many nodes","Joining multiple heterogeneous databases via a federated query engine layer","Replicating a single database across multiple geographic availability zones"),
110:("Trie in memory or Redis Sorted Sets with prefix matching and top-N","Query full-text search index on every individual character keystroke","Linear scan every record in the database against each keystroke input","Hash map storing every possible prefix string mapped to result list"),
111:("Probes backend servers periodically and removes unhealthy from traffic rotation","Monitors server CPU temperature and throttles traffic when threshold exceeded","Authenticates incoming client requests before routing to backend service","Caches frequently-requested response payloads to reduce backend load"),
112:("Centralized Redis session store shared across all application server instances","Store sessions in each individual app server local in-process memory","Use stateless JWT tokens that are always valid with no revocation","Route same user always to same server using sticky LB sessions"),
113:("Blocking protocol — coordinator failure leaves participants locked and waiting","Requires all nodes online simultaneously — a 2-node dependency constraint","A write protocol for LSM-tree sequential log-structured compaction merges","An eventually-consistent cache invalidation strategy for distributed systems"),
114:("Probabilistic membership testing — no false negatives, possible false positives","Lossless compression algorithm for reducing message payload storage size","A distributed cache eviction policy using frequency-based scoring tiers","A load balancing algorithm distributing traffic by consistent IP hashing"),
115:("Vertical adds CPU/RAM to one machine; Horizontal adds more machines","No real difference — both approaches achieve identical throughput outcomes","Horizontal scaling is always faster due to inherent parallel processing","Vertical scaling applies only to database tiers, never application tiers"),
116:("Logs changes before applying — enables crash recovery and replication","Pre-writes and optimizes all incoming queries before executing them","Caches all write operations in memory before batching disk persistence","Compresses write operations to reduce storage volume and replication cost"),
117:("Fan-out on write pushing to followers or fan-out on read pulling","Query all followed accounts in real-time on every single page load","Store all posts in one globally sorted and immutable data structure","Full-text search query executed against all posts on every load"),
118:("Sidecar proxy auto-collects metrics, traces, and access logs without code changes","Stores all application logs centrally in a dedicated database per service","Provides only application-level business metrics requiring manual annotation","Replaces all APM tools with a unified mesh-layer monitoring solution"),
119:("Quick capacity calculations to validate design choices and spot bottlenecks","Approximate cloud infrastructure cost estimation for finance and budget","Formal mathematical correctness proof for distributed system consistency","Database query cost estimation using EXPLAIN ANALYZE output analysis"),
120:("Sync waits for replica ack before commit; Async commits without waiting","No meaningful difference — both provide identical durability and latency","Synchronous replication always introduces instability and data corruption risk","Asynchronous replication guarantees zero data loss via write-ahead logging"),
121:("Decouples payment capture from downstream processing ensuring reliability and retry","Speeds up payment authorization by parallelizing pre-validation of cards","Stores encrypted PCI-DSS compliant payment card data durably at rest","Replaces the payment gateway to reduce per-transaction processing fees"),
122:("Leader election for exactly-once execution, jobs in DB, workers via queue","Single cron server running all jobs with redundant hardware for HA","All servers run the same job simultaneously relying on deduplication","Application-level timers in each service with no central coordination"),
123:("Simultaneous instance restarts overwhelm downstream services with burst traffic","Too many microservice instances competing for Kubernetes CPU resource limits","Excessive database indexes causing lock contention under heavy write load","Large payload transfers between services causing network congestion spikes"),
124:("Backward-compatible API evolution — old clients keep working with new features","Rate limit individual API versions to prevent version-specific traffic abuse","Authenticate different client types using version-specific token schemes","Cache response payloads separately for each API version independently"),
125:("Data lake stores raw unstructured data; warehouse stores structured processed data","Data lakes are smaller; warehouses store large enterprise-scale datasets","Data warehouses are significantly cheaper for large-scale analytical queries","Data lakes only process real-time streaming data arriving from Kafka"),
126:("HashMap not thread-safe; ConcurrentHashMap uses bucket-level locking for safety","No functional difference in modern Java — both collections are thread-safe","ConcurrentHashMap is always slower due to synchronization overhead added","HashMap uses CAS operations; ConcurrentHashMap uses synchronized blocks"),
127:("Volatile write in thread A is visible to thread B after reading","A garbage collection ordering rule applied during object finalization phase","A method execution ordering rule enforced at JIT compilation time","The JVM class-loading and static initialization ordering sequence rule"),
128:("Visibility guarantee — reads/writes go to main memory preventing CPU caching","Atomic compound operations like increment and compare-and-swap automatically","Thread-safe collection access operations without needing external synchronization","Immutability — the variable reference cannot be changed after initial assignment"),
129:("Work-stealing scheduler optimized for recursive divide-and-conquer parallel tasks","No functional difference — both use a shared queue equally well","ForkJoinPool exclusively designed for I/O-bound asynchronous callback tasks","ThreadPoolExecutor supports recursive task splitting; ForkJoinPool does not"),
130:("JVM-managed lightweight thread enabling millions of concurrent I/O operations","A thread that executes only inside a virtual machine monitor environment","A deprecated Java 8 feature since replaced by CompletableFuture chaining","A specialized thread pool exclusively for CPU-bound parallel computation tasks"),
131:("Checked must be declared or caught; unchecked RuntimeException needs no handling","No runtime behavioral difference between checked and unchecked types exists","Unchecked exceptions always terminate the entire JVM on propagation path","Checked exceptions are Java-only — absent in Kotlin Scala and Groovy"),
132:("G1GC has configurable pause target; ZGC concurrent with sub-millisecond pauses","No meaningful difference in modern JVMs — both GCs perform identically","ZGC is only suitable for development; G1GC required in production","G1GC handles significantly larger heap sizes than ZGC supports today"),
133:("Suspends current transaction and starts a completely new independent transaction","Always joins an existing transaction and never creates a new one","Runs the annotated method entirely without any transactional context wrapping","Creates a new transaction only when no existing active transaction exists"),
134:("thenApply maps result synchronously; thenCompose flat-maps to another future","Identical methods — use either interchangeably for chaining async operations","thenCompose always executes synchronously blocking the calling thread entirely","thenApply handles errors only; thenCompose handles successful completions only"),
135:("Production endpoints for health, metrics, info integrating with Prometheus/Grafana","A unit and integration testing library specific to Spring Boot context","A Maven and Gradle build plugin that packages Spring Boot jars","A database schema migration tool similar to Liquibase or Flyway"),
136:("RestController equals Controller plus ResponseBody auto-serializing return to JSON","RestController only for RESTful APIs with no HTML view rendering","Controller handles HTTP requests; RestController handles WebSocket connections only","No functional difference in Spring 5+ — both annotations are interchangeable"),
137:("Intermediate ops lazy — execute only when terminal operation is invoked","Stream executes all operations eagerly immediately when each operator chains","Lazy evaluation applies exclusively to parallel streams not sequential streams","Lazy evaluation causes OutOfMemoryError for large input stream pipelines"),
138:("ReentrantLock adds tryLock, timed lock, interruptible, and fairness options","Identical in all use cases — ReentrantLock adds no extra capabilities","synchronized always faster due to JVM-intrinsic and escape analysis optimization","ReentrantLock does not support reentrant locking unlike synchronized blocks"),
139:("Fastest JDBC connection pool with minimal overhead and built-in JMX metrics","An ORM framework mapping Java objects to relational database table rows","A native PostgreSQL JDBC driver with advanced query plan optimization","A distributed query result cache layer to reduce database read load"),
140:("Makes null handling explicit in API; misuse is using as method parameter","Reduces heap memory usage by boxing values only when non-null required","Replaces every null check making NullPointerException completely impossible in code","Makes all method calls faster by eliminating null pointer check overhead"),
141:("Lightweight JVM-managed green threads; M:N scheduling on M OS threads","A native OS kernel thread with full context-switch scheduling overhead","An async/await coroutine function requiring an explicit event loop pump","A coroutine requiring explicit cooperative yield calls to share execution"),
142:("Unbuffered blocks sender until receiver ready; buffered blocks only when full","A global shared variable safe for inter-goroutine communication by design","Buffered and unbuffered channels behave identically in all usage scenarios","Buffered channels always slower due to extra buffer management overhead"),
143:("Registers a deferred call to run when enclosing function returns LIFO","Delays compilation of the function body until first invocation occurs","Runs a goroutine asynchronously in background without blocking the caller","Defers all error handling responsibility entirely to the calling function"),
144:("Any type with the required methods satisfies the interface implicitly","Go requires explicit implements keyword declaration like Java and C#","Go interfaces support struct-to-struct inheritance for method promotion","Go interfaces must be registered with the runtime reflection system"),
145:("Returns errors as values — caller must check explicitly, no exceptions","Go uses try/catch blocks identical to Java exception handling model","Go panics on every error including normal recoverable domain conditions","Go has a checked exception model enforced by the Go compiler"),
146:("Counter-based sync — waits for all goroutines in the group to finish","Synchronizes concurrent goroutine access to shared mutable memory variables","Creates a reusable pool of pre-spawned goroutines for parallel execution","Hard-limits the maximum number of goroutines that can run concurrently"),
147:("Build/test flag that instruments code to detect concurrent data races","A CPU and memory performance profiler for goroutine execution analysis","A static analysis tool detecting data races without any code execution","A memory leak detector identifying goroutines that never terminate cleanly"),
148:("Carries deadlines, cancellation signals, and request-scoped values across API boundaries","Stores global application configuration accessible from all goroutines safely","A dependency injection container managing service and repository instance lifecycles","A structured logging framework for adding request-scoped fields to logs"),
149:("Composition via embedding — promoted methods but no is-a relationship","Identical to Java class inheritance — embedded type is always a child","A mechanism for inheriting from multiple parent structs simultaneously","Pure syntactic sugar with no functional or runtime behavioral difference"),
150:("Concurrent tricolor mark-and-sweep GC targeting sub-millisecond STW pauses","Go uses reference counting like Python requiring no stop-the-world pauses","Go has no garbage collector — all memory freed manually via unsafe","Go uses generational GC like Java with Eden Survivor and Old gen"),
}

letters = ['A','B','C','D']

def apply(q):
    qid = q['id']
    if qid not in N:
        return q
    correct, w1, w2, w3 = N[qid]
    ans_idx = letters.index(q['answer'])
    wrongs = [w1, w2, w3]
    texts = list(wrongs)
    texts.insert(ans_idx, correct)
    q2 = dict(q)
    q2['options'] = [f"{letters[i]}. {texts[i]}" for i in range(4)]
    return q2

new_qs = [apply(q) for q in ALL_QUESTIONS]

topic_headers = {
    1:   "# ── MICROSERVICES (1-25) " + "─"*53,
    26:  "# ── MESSAGING QUEUES (26-50) " + "─"*49,
    51:  "# ── REDIS / CACHE (51-75) " + "─"*52,
    76:  "# ── DATABASES (76-100) " + "─"*55,
    101: "# ── SYSTEM DESIGN (101-125) " + "─"*50,
    126: "# ── JAVA (126-140) " + "─"*58,
    141: "# ── GO (141-150) " + "─"*60,
}

lines = ['"""q_data.py — 150 MCQs for 5-yr Java/Go backend engineers (product companies)."""\n\nALL_QUESTIONS = [\n']
for q in new_qs:
    if q['id'] in topic_headers:
        lines.append(f"\n{topic_headers[q['id']]}\n")
    lines.append(json.dumps(q, ensure_ascii=False) + ',\n')
lines.append(']\n')

with open('q_data.py', 'w', encoding='utf-8') as f:
    f.write(''.join(lines))

dist = {}
for q in new_qs:
    dist[q['answer']] = dist.get(q['answer'], 0) + 1
print("Answer dist:", dict(sorted(dist.items())))
print(f"Done — {len(new_qs)} questions patched with balanced options.")
